version: '3.8'

services:
  static-site:
    build:
      context: .
      dockerfile: Dockerfile-static
    ports:
      - "8080:80"
    networks:
      - app-network

  dotnet-app:
    build:
      context: .
      dockerfile: Dockerfile-dotnet
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
